[package]
name = 'waywiserrr'
version = '0.1.0'
edition = '2018'

[lib]
crate-type = [ 'staticlib' ]

[dependencies]
extendr-api = {version = '0.4', features = ["ndarray"]}
ndarray = {version = '0.15.6', features = ["rayon"]}
ndarray-stats = '0.5.1'
